name: Test Download

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download from Google Drive
        run: |
          pip install gdown
          FILE_ID="1DEqIDZXqw7L9bGyA4iBlAQXVJTpww9HT"
          gdown "https://drive.google.com/uc?id=$FILE_ID" -O project.zip
          ls -la
          unzip -l project.zip  # Lihat isi ZIP tanpa ekstrak
